# .goreleaser.yml
# Build customization
project_name: gscript
builds:
  - main: ./cmd/gscript/main.go
    binary: gscript
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -s
# Archive customization
archive:
  format: zip
